Move twilio channel logic to server side
Hey-Mentor/apis pull request #27
Opened 2019-12-06 04:36 UTC by fredrifo

2020-02-19 21:21 UTC, bongiovimatthew requested changes

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +    ? process.env.TWILIO_CHAT_SERVICE_SID
This should be `TWILIO_ACCOUNT_SID` and `TEST_TWILIO_ACCOUNT_SID`

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +    const allValid = userIds.forEach(element => UserValidation.ValidateChatUser(element, true));
Can we take the `true` out of `ValidateChatUser` and make two validate functions, one for true and one for false, with names like `ValidateChatUserExists` and `ValidateChatUserDoesNotExist`?

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +    // TODO: Create the actual channel in Twilio
This TODO comment and the next one can be removed

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +    const newChannel = await client.chat
Can we move the `client` calls into `twilio.js` and remove the consts for TWILIO_... at the top (since they are in `twilio.js` already)?

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +exports.addMemberToChannel = async function (channelSId, userId) {
Can we move `addMemberToChannel` to `twilio.js` too?

2020-02-19 21:21 UTC, bongiovimatthew commented on middleware/auth.js
> +exports.adminAuthorize = function (req, res, next) {
Could we add a few tests to either test/auth_test.js or a new test/admin_auth_tests.js to check the admin authorization with requests?

2020-02-19 21:21 UTC, bongiovimatthew commented on controllers/chat.js
> +    // TODO: Check if each user already has a channel created, and skip if needed
I don't think we're doing this check yet. Can we add that?

2020-02-21 13:51 UTC, wahabtrimulabs commented on controllers/chat.js
> +    ? process.env.TWILIO_CHAT_SERVICE_SID
yes found that

2020-02-22 12:25 UTC, bongiovimatthew commented on models/users.js
> +            enum: ['mentor', 'mentee'],
We should add 'admin' to this enum

2020-02-22 12:25 UTC, bongiovimatthew commented on tools/db_util.js
> +        throw new Error(`Mock data lacking schema property hello : ${path}`);
I think this might have been left over from testing

2020-03-25 18:25 UTC, closed without merging